var date=new Date();
console.log(date);
var month=date.getMonth();
console.log(month);
var year=date.getFullYear();
console.log(year);
var currentdate=date.getDate();
console.log(currentdate);
var currentmonth=date.getMonth();
console.log(currentmonth);
var currenthour=date.getHours();
console.log(currenthour);
var currentminute=date.getMinutes();
console.log(currentminute);
var currentsec=date.getMilliseconds();
console.log(currentsec);